### ISSUE TITLE
RCON configuration causes 100% CPU spike and cannot connect to server

### ISSUE THREAD

**Issue by drephuz** [StunlockStudios/vrising-dedicated-server-instructions#70]
I added the configuration for RCON to the JSON file for the serverhostsettings.json file, and the behavior in the task manager showed it was peaking at 100%.  Could not connect until I removed the RCON configuration and restarted the server.  

PS: I waited about 8 minutes before I gave up on waiting for reconnect.

```
{
  "Name": "Dreph Rising",
  "Description": "",
  "Port": 9876,
  "QueryPort": 9877,
  "MaxConnectedUsers": 40,
  "MaxConnectedAdmins": 4,
  "ServerFps": 30,
  "SaveName": "Drepheim",
  "Password": "redacted",
  "Secure": true,
  "ListOnMasterServer": true,
  "AutoSaveCount": 30,
  "AutoSaveInterval": 120,
  "GameSettingsPreset": "",
  "AdminOnlyDebugEvents": true,
  "DisableDebugEvents": false
  "Rcon": {
  "Enabled": true,
  "Password": "redacted",
  "Port": 54321
}
}
```

**Comment by DearScorpion** [comment]
It's likely because you're missing a , after "DisableDebugEvents": false - "DisableDebugEvents": false,
`{
  "Name": "Dreph Rising",
  "Description": "",
  "Port": 9876,
  "QueryPort": 9877,
  "MaxConnectedUsers": 40,
  "MaxConnectedAdmins": 4,
  "ServerFps": 30,
  "SaveName": "Drepheim",
  "Password": "redacted",
  "Secure": true,
  "ListOnMasterServer": true,
  "AutoSaveCount": 30,
  "AutoSaveInterval": 120,
  "GameSettingsPreset": "",
  "AdminOnlyDebugEvents": true,
  "DisableDebugEvents": false,
  "Rcon": {
  "Enabled": true,
  "Password": "redacted",
  "Port": 54321
}
}`
Should allow it to parse the file correctly.
